ARG Version
FROM almalinux:${Version:-8}
ARG COURSE="Docker" \
    TRAINER="Sivakumar" \
    DURATION="10HRS" \
    AUTHOR="joindevops"
  Run echo "Trainer is ${TRAINER} and Version is : ${Version}"
  CMD ["sleep","100"]
